name: Lint Code Base

# Trigger for the workflow for push and pull_request events for branches test and main
# on: [push, pull_request]
on:
  push:
    branches: [test, main]
  pull_request:
    branches: [test] # when pulling from test branch to other branches

permissions: read-all # prevent unrestricted access to the repository with "write-all"

# workflow (made up of jobs) runs on trigger
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write    

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0
      
      - name: Super-linter (MAIN)
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true # checks all files in the repo. Set to false to only check changed / edited files

          VALIDATE_NATURAL_LANGUAGE: false
          VALIDATE_MARKDOWN: false

      - name: Super-linter (EXTRA) FOR README and language
        uses: super-linter/super-linter@v6.6.0  # x-release-please-version
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false # checks all files in the repo. Set to false to only check changed / edited files

          VALIDATE_NATURAL_LANGUAGE: true
          TEXTLINT_RULES_PATH: ./.textlintrc # path to textlint rules
          
          VALIDATE_MARKDOWN: true
          MARKDOWN_LINTER_RULES_PATH: ./.markdownlint-lint.yml # path to markdownlint rules